language: php

php:
  - '7.3'
  - '7.4'
  - 'nightly'

matrix:
  fast_finish: true
  allow_failures:
    - php: nightly

branches:
  only:
    - master

before_script:
  - composer self-update
  - composer require php-coveralls/php-coveralls
  - composer install --no-interaction --no-ansi --no-progress --no-suggest

script:
  - ./vendor/bin/phpunit --coverage-clover ./tests/logs/clover.xml

after_success:
  - travis_retry php vendor/bin/php-coveralls -v
