language: php

php:
  - '7.2'
  - '7.3'
  - '7.4'
  - 'nightly'

matrix:
  fast_finish: true
  allow_failures:
    - php: nightly

branches:
  only:
    - master

before_script:
  - composer self-update
  - composer install --no-interaction --no-ansi --no-progress --no-suggest

script:
  - ./vendor/bin/phpunit
